version: 2

models:
  - name: dim_channels
    description: Dimension table for Telegram channels
    columns:
      - name: channel_key
        description: Surrogate key for channel
        tests:
          - unique
          - not_null
      - name: channel_name
        description: Username of the channel
        tests:
          - not_null

  - name: dim_dates
    description: Date dimension for time analysis
    columns:
      - name: date_key
        description: YYYYMMDD format key
        tests:
          - unique
          - not_null

  - name: fct_messages
    description: Fact table - one row per message
    columns:
      - name: message_id
        tests:
          - not_null
      - name: channel_key
        tests:
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        tests:
          - relationships:
              to: ref('dim_dates')
              field: date_key